import "reflect-metadata";
import { Container } from "inversify";
import TYPES from "../constants/types";
import CategoryController from "../controllers/implementations/category-controller";
import ICategoryController from "../controllers/interfaces/category-controller.interface";
import DashboardController from "../controllers/implementations/dashboard-controller";
import IDashboardController from "../controllers/interfaces/dashboard-controller.interface";
import TemplateController from "../controllers/implementations/template-controller";
import ITemplateController from "../controllers/interfaces/template-controller.interface";
import ThemeController from "../controllers/implementations/theme-controller";
import IThemeController from "../controllers/interfaces/theme-controller.interface";
import WorkController from "../controllers/implementations/work-controller";
import IWorkController from "../controllers/interfaces/work-controller.interface";
import CategoryRepository from "../repositories/implementations/category-repository";
import ICategoryRepository from "../repositories/interfaces/category-repository.interface";
import TemplateRepository from "../repositories/implementations/template-repository";
import ITemplateRepository from "../repositories/interfaces/template-repository.interface";
import ThemeRepository from "../repositories/implementations/theme-repository";
import IThemeRepository from "../repositories/interfaces/theme-repository.interface";
import RefreshTokenRepository from "../repositories/implementations/refresh-token-repository";
import IRefreshTokenRepository from "../repositories/interfaces/refresh-token-repository.interface";
import UserRepository from "../repositories/implementations/user-repository";
import IUserRepository from "../repositories/interfaces/user-repository.interface";
import WorkRepository from "../repositories/implementations/work-repository";
import IWorkRepository from "../repositories/interfaces/work-repository.interface";
import AccountSecurityController from "../controllers/implementations/account-security-controller";
import SmtpEmailSender from "../services/implementations/smtp-email-sender";
import IEmailSender from "../services/interfaces/email-sender.interface";
import EmailVerificationService from "../services/implementations/email-verification-service";
import IEmailVerificationService from "../services/interfaces/email-verification-service.interface";
import GoogleAuthController from "../controllers/implementations/google-auth-controller";
import GoogleAuthService from "../services/implementations/google-auth-service";
import IGoogleAuthService from "../services/interfaces/google-auth-service.interface";
import GoogleIdentityProvider from "../services/implementations/google-identity-provider";
import IGoogleIdentityProvider from "../services/interfaces/google-identity.interface";
import PasswordResetService from "../services/implementations/password-reset-service";
import IPasswordResetService from "../services/interfaces/password-reset-service.interface";
import SessionController from "../controllers/implementations/session-controller";
import SessionService from "../services/implementations/session-service";
import ISessionService from "../services/interfaces/session-service.interface";
import AuthController from "../controllers/implementations/auth-controller";
import IAuthController from "../controllers/interfaces/auth-controller.interface";
import AuthService from "../services/implementations/auth-service";
import IAuthService from "../services/interfaces/auth-service.interface";
import PasswordService from "../services/implementations/password-service";
import IPasswordService from "../services/interfaces/password-service.interface";
import TokenService from "../services/implementations/token-service";
import ITokenService from "../services/interfaces/token-service.interface";
import CategoryService from "../services/implementations/category-service";
import ICategoryService from "../services/interfaces/category-service.interface";
import DashboardService from "../services/implementations/dashboard-service";
import IDashboardService from "../services/interfaces/dashboard-service.interface";
import TemplateService from "../services/implementations/template-service";
import ITemplateService from "../services/interfaces/template-service.interface";
import ThemeService from "../services/implementations/theme-service";
import IThemeService from "../services/interfaces/theme-service.interface";
import WorkService from "../services/implementations/work-service";
import IWorkService from "../services/interfaces/work-service.interface";

const container = new Container();

container.bind<ICategoryRepository>(TYPES.ICategoryRepository).to(CategoryRepository);
container.bind<ICategoryService>(TYPES.ICategoryService).to(CategoryService);
container.bind<ICategoryController>(TYPES.ICategoryController).to(CategoryController);

container.bind<ITemplateRepository>(TYPES.ITemplateRepository).to(TemplateRepository);
container.bind<ITemplateService>(TYPES.ITemplateService).to(TemplateService);
container.bind<ITemplateController>(TYPES.ITemplateController).to(TemplateController);

container.bind<IThemeRepository>(TYPES.IThemeRepository).to(ThemeRepository);
container.bind<IThemeService>(TYPES.IThemeService).to(ThemeService);
container.bind<IThemeController>(TYPES.IThemeController).to(ThemeController);

container.bind<IWorkRepository>(TYPES.IWorkRepository).to(WorkRepository);
container.bind<IWorkService>(TYPES.IWorkService).to(WorkService);
container.bind<IWorkController>(TYPES.IWorkController).to(WorkController);

container.bind<IUserRepository>(TYPES.IUserRepository).to(UserRepository);
container.bind<IRefreshTokenRepository>(TYPES.IRefreshTokenRepository).to(RefreshTokenRepository);
container.bind<IPasswordService>(TYPES.IPasswordService).to(PasswordService);
container.bind<ITokenService>(TYPES.ITokenService).to(TokenService);
container.bind<IEmailSender>(TYPES.IEmailSender).to(SmtpEmailSender);
container.bind<IEmailVerificationService>(TYPES.IEmailVerificationService).to(EmailVerificationService);
container.bind<IPasswordResetService>(TYPES.IPasswordResetService).to(PasswordResetService);
container.bind<IGoogleIdentityProvider>(TYPES.IGoogleIdentityProvider).to(GoogleIdentityProvider);
container.bind<IGoogleAuthService>(TYPES.IGoogleAuthService).to(GoogleAuthService);
container.bind<ISessionService>(TYPES.ISessionService).to(SessionService);
container.bind<IAuthService>(TYPES.IAuthService).to(AuthService);
container.bind<IAuthController>(TYPES.IAuthController).to(AuthController);
container.bind<GoogleAuthController>(TYPES.IGoogleAuthController).to(GoogleAuthController);
container.bind<AccountSecurityController>(TYPES.IAccountSecurityController).to(AccountSecurityController);
container.bind<SessionController>(TYPES.ISessionController).to(SessionController);
container.bind<IDashboardService>(TYPES.IDashboardService).to(DashboardService);
container.bind<IDashboardController>(TYPES.IDashboardController).to(DashboardController);

export default container;
